name: UI tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build UI tests
      run: xcodebuild build-for-testing -scheme whatdid-ui-test
    - name: Run UI tests
      run: xcodebuild test-without-building -scheme whatdid-ui-test
